a = Analysis(
    ["main.py"],
    binaries=[],
    datas=[],
    excludes=[],
    hiddenimports=[],
    hooksconfig={},
    hookspath=[],
    noarchive=False,
    optimize=0,
    pathex=[],
    runtime_hooks=[],
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    argv_emulation=False,
    bootloader_ignore_signals=False,
    codesign_identity=None,
    console=False,
    debug=False,
    disable_windowed_traceback=False,
    entitlements_file=None,
    name="main",
    runtime_tmpdir=None,
    strip=False,
    target_arch=None,
    upx_exclude=[],
    upx=True,
)
app = BUNDLE(
    exe,
    bundle_identifier=None,
    icon=None,
    name="main.app",
)
